### ISSUE TITLE
Extension common issues faced on daily basis

### ISSUE THREAD

**Issue by Kruts17** [microsoft/azure-boards-estimate#70] opened 2022-01-18 23:35 UTC
1.	Only a limited number of users are able to point the user stories
a.	This is very inconsistent
b.	Sometimes only 2 members are able to point and sometimes 6-7 are able to point
c.	For example, if we have 10 members pointing a user story, only 6 show up as pointed and we keep waiting for the other 4 to point, but they have already pointed. It just doesn't show up
2.	Revealing the story points
a.	More often than not, when we click the ‘Reveal’ button, the screen goes blank and then to the homepage
b.	This is also inconsistent
c.	Sometimes, the revel button works. But most of the time it doesn’t work
3.	Performance
a.	When we click on a session, the page takes forever to load
b.	Very often, we see this error
![image](https://user-images.githubusercontent.com/97994543/150035960-75a21c15-bcbb-4f01-808a-4acf525e5784.png)

c.	It loads for some users, and it wouldn’t load for others
4.	Sessions Page
a.	When a new session is created, this is added as a card in this page
b.	How the cards are ordered in this page is not clear. It is neither in an alphabetical order, nor or date/time created
c.	Trying to find the session is very painful
5.	Session created on a query
a.	We have a query to retrieve all the user stories in a specific area path that have not been pointed. We also have set a sort order on stackrank
b.	When the user stories are listed in a session, they are sometimes missing some user stories or in an adhoc manner, they are sorted differently

All the above issues, we have tried with multiple browsers, incognito mode, clearing cache. But same behavior.

**Comment by Kruts17** [comment] 2022-02-03 17:44
@MOlausson any suggestions or i/p's you can help with?

**Comment by MOlausson** [comment] 2022-02-03 21:47
@Kruts17 thanks for the feedback. We're reviewing, will come back with our responses.

**Comment by udayansarma** [comment] 2022-09-19 23:59
Is there an update to this issue?

**Comment by AminTi** [comment] 2022-09-21 18:00
Hi, It should be fixed I couldn't reproduce the bugs, if you  still facing the same issue let me know. We can schedule a Teams meeting.

**Closed by AminTi** 2022-09-21 18:01 UTC
Labels: bug

**Comment by udayansarma** [comment] 2022-11-15 00:29
Hi @AminTi, one of my customer is still able to reproduce the behavior, happy to give you a quick demo. Please let me know how we can get on a conference call. Thanks much

**Comment by AminTi** [comment] 2022-11-15 19:52
Hi! here is my email amin.titi@solidify.dev
