### ISSUE TITLE
Connecting to server.. on Microsoft Azure > Boards > Estimate

### ISSUE THREAD

**Issue by Svashly** [microsoft/azure-boards-estimate#321] opened 2024-04-23 14:13 UTC
We have same issue on azure > Boards > Estimate
First you see
`Loading work items..`
then you see
`Connecting to server..`
<img width="1598" alt="image" src="https://github.com/microsoft/azure-boards-estimate/assets/144381973/342198f2-d378-4e0b-be03-c8665e2e64d9">

Link Example:
https://dev.azure.com/companyName/ProjectName/_apps/hub/ms-devlabs.estimate.estimate-hub#/session/xyyyyyy/LV-2024-A3

**Comment by AminTi** [comment] 2024-04-25 13:19
Hi, we are working on it. This issue is a duplicate of #309.

**Closed by AminTi** 2024-04-25 13:19 UTC
